x-template:
  dev-service: &dev
    volumes:
      - ./:/home/app
      - back-packages:/home/app/back/node_modules
      - front-packages:/home/app/front/node_modules

services:
  back:
    <<: *dev
    command: /bin/sh -c "while sleep 50400; do :; done"
    privileged: true
    ports:
      - 9229:9229
      - 3002:3002
      - 8229:8228

  front:
    <<: *dev
    command: /bin/sh -c "while sleep 50400; do :; done"
    ports:
      - 4201:4201
      - 8228:8228

volumes:
  back-packages:
  front-packages:
