services:
  front:
    image: front
    build:
      context: ./front
    ports:
      - "4200:4200"
    volumes:
      - ./front:/app
    restart: always
    networks:
      - napoli-network
    depends_on:
      - back

  back:
    image: back
    build:
      context: ./back
    ports:
      - "3000:3000"
    volumes:
      - ./back:/app
    depends_on:
      db:
        condition: service_healthy
    environment:
       JWT_SECRETS: fafafa_1911725362!@#_wow!@WECJKBD
    networks:
      - napoli-network
    restart: on-failure

  db:
    image: postgres:17.2-alpine3.21
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: amirali0448v
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data    
    restart: unless-stopped
    networks:
      - napoli-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 3s
      retries: 5

networks:
  napoli-network:
    driver: bridge
